freebasic: init at 1.07.3 & unstable-2019-07-30
Upstream has incomplete support for Darwin and bootstrapping needs a
working fbc compiler or an archive with precompiled sources.

Precompiled freebasic provided by OHRRPGCE devs:
https://rpg.hamsterrepublic.com/ohrrpgce/Compiling_in_Mac_OS_X

Fork with improved Darwin support:
https://github.com/rversteegen/fbc/tree/mac

I haven't managed to get it to compile with LLVM yet, may need to use
GCC on Darwin:

> FBC src/compiler/obj/darwin-x86_64/ast-gosub.ll:194:1:
> error: redefinition of type